using SmcManager.Core.Models;
using SmcManager.Core.Services;

namespace SmcManager.Infrastructure.Download;

/// <summary>
/// Временный файл cookies Netscape для yt-dlp.
/// </summary>
internal static class YtdlpCookieHelper
{
    public static async Task<string?> WriteCookieFileAsync(
        SocialAccount? account,
        CancellationToken cancellationToken)
    {
        var cookieHeader = account is null ? null : SocialAccountAuth.BuildCookieHeader(account);
        if (string.IsNullOrWhiteSpace(cookieHeader))
            return null;

        var domains = account.Platform switch
        {
            Core.Enums.SocialPlatform.Instagram => new[] { ".instagram.com", "www.instagram.com" },
            Core.Enums.SocialPlatform.YouTube => new[] { ".youtube.com", "www.youtube.com" },
            Core.Enums.SocialPlatform.Vkontakte => new[] { ".vk.com", "vk.com" },
            _ => Array.Empty<string>()
        };

        if (domains.Length == 0)
            return null;

        var path = Path.Combine(Path.GetTempPath(), $"smc-cookies-{account.Id}-{Guid.NewGuid():N}.txt");
        var lines = new List<string> { "# Netscape HTTP Cookie File", "# Generated by SmcManager" };

        foreach (var part in cookieHeader.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var eq = part.IndexOf('=');
            if (eq <= 0) continue;

            var name = part[..eq].Trim();
            var value = SanitizeCookieValue(part[(eq + 1)..].Trim());
            if (string.IsNullOrEmpty(name)) continue;

            foreach (var domain in domains)
            {
                // Netscape: домен с точкой (.instagram.com) → TRUE (все поддомены), host-only → FALSE
                var includeSubdomains = domain.StartsWith('.') ? "TRUE" : "FALSE";
                lines.Add($"{domain}\t{includeSubdomains}\t/\tTRUE\t2147483647\t{name}\t{value}");
            }
        }

        await File.WriteAllLinesAsync(path, lines, cancellationToken);
        return path;
    }

    private static string SanitizeCookieValue(string value)
    {
        if (value.Contains('%'))
        {
            try { value = Uri.UnescapeDataString(value); }
            catch (UriFormatException) { /* оставляем как есть */ }
        }

        return value
            .Replace('\t', ' ')
            .Replace('\r', ' ')
            .Replace('\n', ' ');
    }

    public static void TryDelete(string? path)
    {
        if (string.IsNullOrEmpty(path)) return;
        try { File.Delete(path); } catch { /* ignore */ }
    }
}
